import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Navbar from '../components/navbar/navbar.component';
import SessionWrapper from '../components/session-wrapper/session-wrapper.component';
import Link from 'next/link';
import Footer from '../components/footer/footer.component';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html className='h-full' lang='en'>
        <body className={`h-full ${inter.className}`}>
          <div className='flex flex-col h-full'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
